# Running tests with options(warn = 2) to fail on test warnings
on:
  pull_request:
    branches: [main, master]

name: check-vignette-warnings

jobs:
  check-vignette-warnings:
    uses: easystats/workflows/.github/workflows/check-vignette-warnings.yaml@main
