# Running tests with options(warn = 2) to fail on test warnings
on:
  pull_request:
    branches: [main, master]

name: check-test-warnings

jobs:
  check-test-warnings:
    uses: easystats/workflows/.github/workflows/check-test-warnings.yaml@main
