# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]

name: html-5-check

jobs:
  html-5-check:
    uses: easystats/workflows/.github/workflows/html-5-check.yaml@main
